# Import of Libraries

In [49]:
import numpy as np
import pandas as pd

# Load of Datasets

In [50]:
matches = pd.read_csv("../data/raw_data/ipl_matches_data.csv", encoding="latin1")
deliveries = pd.read_csv("../data/raw_data/ball_by_ball_data.csv", encoding="latin1")

# Data Preparation

In [51]:
matches.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,335982,2008,6,Bangalore,18-04-2008,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN
1,1082591,2017,6,Hyderabad,05-04-2017,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,15.0,win,NaN
2,1082592,2017,6,Pune,06-04-2017,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,NaN,7.0,36.0,win,NaN
3,1082593,2017,6,Rajkot,07-04-2017,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,NaN,10.0,57.0,win,NaN
4,1082594,2017,6,Indore,08-04-2017,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,NaN,6.0,71.0,win,NaN

In [52]:
matches.shape

(1169, 24)

In [53]:
deliveries.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [54]:
deliveries.shape

(278205, 30)

- <b>Total score in each innings in every matches.

In [55]:
total_score_df = deliveries.groupby(['match_id','innings']).sum()['total_runs'].reset_index()

In [56]:
print(total_score_df)

      match_id  innings  total_runs
0       335982        1         222
1       335982        2          82
2       335983        1         240
3       335983        2         207
4       335984        1         129
...        ...      ...         ...
2360   1473510        2         207
2361   1473511        1         190
2362   1473511        2         184
2363   1485779        1         206
2364   1485779        2         208

[2365 rows x 3 columns]

In [57]:
total_score_df = total_score_df[total_score_df['innings']==1]

In [58]:
total_score_df

      match_id  innings  total_runs
0       335982        1         222
2       335983        1         240
4       335984        1         129
6       335985        1         165
8       335986        1         110
...        ...      ...         ...
2355   1473508        1         101
2357   1473509        1         228
2359   1473510        1         203
2361   1473511        1         190
2363   1485779        1         206

[1169 rows x 3 columns]

In [59]:
match_df = matches.merge(total_score_df[['match_id','total_runs']], left_on='match_id',right_on='match_id')

In [60]:
match_df.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage,total_runs
0,335982,2008,6,Bangalore,18-04-2008,Indian Premier League,1.0,male,T20,T20,...,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN,222
1,1082591,2017,6,Hyderabad,05-04-2017,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,NaN,15.0,win,NaN,207
2,1082592,2017,6,Pune,06-04-2017,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,NaN,7.0,36.0,win,NaN,184
3,1082593,2017,6,Rajkot,07-04-2017,Indian Premier League,3.0,male,T20,T20,...,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,NaN,10.0,57.0,win,NaN,183
4,1082594,2017,6,Indore,08-04-2017,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,NaN,6.0,71.0,win,NaN,163

In [61]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Punjab Kings',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Rajasthan Royals', 'Chennai Super Kings', 'Lucknow Super Giants',
       'Gujarat Titans', 'Kochi Tuskers Kerala', 'Pune Warriors'],
      dtype=object)

In [62]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Punjab Kings',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals',
    'Gujarat Titans',
    'Lucknow Super Giants'
]

In [63]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [64]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [65]:
match_df.shape

(1053, 25)

In [66]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Mumbai Indians', 'Punjab Kings', 'Kolkata Knight Riders',
       'Delhi Capitals', 'Rajasthan Royals', 'Chennai Super Kings',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype=object)

In [67]:
match_df = match_df[['match_id','city','match_winner','total_runs']]

In [68]:
delivery_df = match_df.merge(deliveries, on='match_id')

In [69]:
delivery_df = delivery_df[delivery_df['innings']==2]

In [70]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120967 entries, 124 to 251122
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           120967 non-null  int64
 1   city               114955 non-null  object
 2   match_winner       120933 non-null  object
 3   total_runs_x       120967 non-null  int64
 4   season_id          120967 non-null  int64
 5   batter             120967 non-null  object
 6   bowler             120967 non-null  object
 7   non_striker        120967 non-null  object
 8   team_batting       120967 non-null  object
 9   team_bowling       120967 non-null  object
 10  over_number        120967 non-null  int64
 11  ball_number        120967 non-null  int64
 12  batter_runs        120967 non-null  int64
 13  extras             120967 non-null  int64
 14  total_runs_y       120967 non-null  int64
 15  batsman_type       120967 non-null  object
 16  bowler_type        120967 non-null  object
 17  player_out         6011 non-null    object
 18  fielders_involved  6011 non-null    object
 19  is_wicket          120967 non-null  bool
 20  is_wide_ball       120967 non-null  bool
 21  is_no_ball         120967 non-null  bool
 22  is_leg_bye         120967 non-null  bool
 23  is_bye             120967 non-null  bool
 24  is_penalty         120967 non-null  bool
 25  wide_ball_runs     120967 non-null  int64
 26  no_ball_runs       120967 non-null  int64
 27  leg_bye_runs       120967 non-null  int64
 28  bye_runs           120967 non-null  int64
 29  penalty_runs       120967 non-null  int64
 30  wicket_kind        6011 non-null    object
 31  is_super_over      120967 non-null  bool
 32  innings            120967 non-null  int64
dtypes: bool(7), int64(14), object(12)
memory usage: 25.7+ MB

- <b> Runs left

In [71]:
# delivery_df.groupby('match_id').cumsum()['total_runs_y']
delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [72]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,current_score
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,0,0,0,0,0,NaN,False,2,1
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,1,0,0,0,0,NaN,False,2,2
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,0,0,0,0,0,NaN,False,2,2
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,0,0,0,0,0,NaN,False,2,3
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,0,0,0,0,0,NaN,False,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,False,0,0,0,0,0,NaN,False,2,199
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,1,0,0,0,0,NaN,False,2,200
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,0,0,0,0,0,NaN,False,2,201
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,False,0,0,0,0,0,NaN,False,2,202
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,0,0,0,0,0,NaN,False,2,208

In [73]:
delivery_df['runs_left'] = delivery_df['total_runs_x'] - delivery_df['current_score'] + 1

In [74]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,current_score,runs_left
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,0,0,NaN,False,2,1,222
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,1,0,0,0,0,NaN,False,2,2,221
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,0,0,NaN,False,2,2,221
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,0,0,NaN,False,2,3,220
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,0,0,NaN,False,2,4,219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,0,0,0,0,NaN,False,2,199,8
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,1,0,0,0,0,NaN,False,2,200,7
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,0,0,0,0,NaN,False,2,201,6
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,0,0,0,0,NaN,False,2,202,5
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,0,0,0,0,NaN,False,2,208,-1

- <b> Balls Left

In [75]:
delivery_df.columns

Index(['match_id', 'city', 'match_winner', 'total_runs_x', 'season_id',
       'batter', 'bowler', 'non_striker', 'team_batting', 'team_bowling',
       'over_number', 'ball_number', 'batter_runs', 'extras', 'total_runs_y',
       'batsman_type', 'bowler_type', 'player_out', 'fielders_involved',
       'is_wicket', 'is_wide_ball', 'is_no_ball', 'is_leg_bye', 'is_bye',
       'is_penalty', 'wide_ball_runs', 'no_ball_runs', 'leg_bye_runs',
       'bye_runs', 'penalty_runs', 'wicket_kind', 'is_super_over', 'innings',
       'current_score', 'runs_left'],
      dtype='object')

In [76]:
delivery_df['over_number'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
delivery_df['balls_bowled'] = delivery_df['over_number'] * 6 + delivery_df['ball_number']
delivery_df['balls_left'] = 120 - delivery_df['balls_bowled']

In [78]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,current_score,runs_left,balls_bowled,balls_left
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,NaN,False,2,1,222,0,120
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,NaN,False,2,2,221,1,119
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,NaN,False,2,2,221,2,118
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,NaN,False,2,3,220,3,117
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,0,0,NaN,False,2,4,219,4,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,0,0,NaN,False,2,199,8,113,7
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,0,0,NaN,False,2,200,7,114,6
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,0,0,NaN,False,2,201,6,115,5
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,0,0,NaN,False,2,202,5,116,4
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,0,0,NaN,False,2,208,-1,117,3

- <b> Wickets left

In [79]:
delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['player_out'].transform(lambda x: x.notnull().cumsum())

delivery_df['wickets_left'] = 10 - delivery_df['wickets_fallen']

In [80]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,penalty_runs,wicket_kind,is_super_over,innings,current_score,runs_left,balls_bowled,balls_left,wickets_fallen,wickets_left
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,NaN,False,2,1,222,0,120,0,10
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,NaN,False,2,2,221,1,119,0,10
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,NaN,False,2,2,221,2,118,0,10
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,NaN,False,2,3,220,3,117,0,10
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,0,NaN,False,2,4,219,4,116,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,NaN,False,2,199,8,113,7,4,6
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,NaN,False,2,200,7,114,6,4,6
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,NaN,False,2,201,6,115,5,4,6
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,0,NaN,False,2,202,5,116,4,4,6
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,0,NaN,False,2,208,-1,117,3,4,6

- <b> Current Run Rate.

In [81]:
# delivery_df['balls_bowled'] = (delivery_df['over_number'] * 6) + delivery_df['ball_number']
# delivery_df['crr'] = (delivery_df['current_score'] * 6) / delivery_df['balls_bowled']

# over number is zero at starting of inning, so handling it can be done by.

delivery_df['balls_bowled'] = (delivery_df['over_number'] * 6) + delivery_df['ball_number']

delivery_df['crr'] = (delivery_df['current_score'] * 6) / delivery_df['balls_bowled'].replace(0, 1)

In [82]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,wicket_kind,is_super_over,innings,current_score,runs_left,balls_bowled,balls_left,wickets_fallen,wickets_left,crr
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,False,2,1,222,0,120,0,10,6.000000
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,False,2,2,221,1,119,0,10,12.000000
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,False,2,2,221,2,118,0,10,6.000000
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,False,2,3,220,3,117,0,10,6.000000
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,NaN,False,2,4,219,4,116,0,10,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,NaN,False,2,199,8,113,7,4,6,10.566372
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,NaN,False,2,200,7,114,6,4,6,10.526316
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,NaN,False,2,201,6,115,5,4,6,10.486957
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,NaN,False,2,202,5,116,4,4,6,10.448276
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,NaN,False,2,208,-1,117,3,4,6,10.666667

- <b> Required Run Rate

In [83]:
delivery_df['rrr'] = (delivery_df['runs_left'] * 6) / delivery_df['balls_left'].replace(0, 1)

In [84]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,is_super_over,innings,current_score,runs_left,balls_bowled,balls_left,wickets_fallen,wickets_left,crr,rrr
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,2,1,222,0,120,0,10,6.000000,11.100000
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,2,2,221,1,119,0,10,12.000000,11.142857
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,2,2,221,2,118,0,10,6.000000,11.237288
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,2,3,220,3,117,0,10,6.000000,11.282051
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,False,2,4,219,4,116,0,10,6.000000,11.327586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,False,2,199,8,113,7,4,6,10.566372,6.857143
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,2,200,7,114,6,4,6,10.526316,7.000000
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,2,201,6,115,5,4,6,10.486957,7.200000
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,False,2,202,5,116,4,4,6,10.448276,7.500000
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,False,2,208,-1,117,3,4,6,10.666667,-2.000000

- <b> Result

In [85]:
def result(row):
    return 1 if row['team_batting']== row['match_winner'] else 0

In [86]:
delivery_df['results'] = delivery_df.apply(result, axis=1)

In [87]:
delivery_df

,match_id,city,match_winner,total_runs_x,season_id,batter,bowler,non_striker,team_batting,team_bowling,...,innings,current_score,runs_left,balls_bowled,balls_left,wickets_fallen,wickets_left,crr,rrr,results
124,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,1,222,0,120,0,10,6.000000,11.100000,0
125,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,2,221,1,119,0,10,12.000000,11.142857,0
126,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,2,221,2,118,0,10,6.000000,11.237288,0
127,335982,Bangalore,Kolkata Knight Riders,222,2008,W Jaffer,AB Dinda,R Dravid,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,3,220,3,117,0,10,6.000000,11.282051,0
128,335982,Bangalore,Kolkata Knight Riders,222,2008,R Dravid,AB Dinda,W Jaffer,Royal Challengers Bangalore,Kolkata Knight Riders,...,2,4,219,4,116,0,10,6.000000,11.327586,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251118,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,Arshdeep Singh,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,2,199,8,113,7,4,6,10.566372,6.857143,1
251119,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,2,200,7,114,6,4,6,10.526316,7.000000,1
251120,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,2,201,6,115,5,4,6,10.486957,7.200000,1
251121,1485779,Jaipur,Delhi Capitals,206,2025,T Stubbs,MP Stoinis,Sameer Rizvi,Delhi Capitals,Punjab Kings,...,2,202,5,116,4,4,6,10.448276,7.500000,1
251122,1485779,Jaipur,Delhi Capitals,206,2025,Sameer Rizvi,MP Stoinis,T Stubbs,Delhi Capitals,Punjab Kings,...,2,208,-1,117,3,4,6,10.666667,-2.000000,1

- <b>Extract useful columns from delivery dataset

In [88]:
final_df = delivery_df[['team_batting','team_bowling','city','runs_left','balls_left','wickets_left','total_runs_x','crr','rrr','results']]

In [89]:
final_df

,team_batting,team_bowling,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,results
124,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,222,120,10,222,6.000000,11.100000,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,119,10,222,12.000000,11.142857,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221,118,10,222,6.000000,11.237288,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,220,117,10,222,6.000000,11.282051,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,219,116,10,222,6.000000,11.327586,0
...,...,...,...,...,...,...,...,...,...,...
251118,Delhi Capitals,Punjab Kings,Jaipur,8,7,6,206,10.566372,6.857143,1
251119,Delhi Capitals,Punjab Kings,Jaipur,7,6,6,206,10.526316,7.000000,1
251120,Delhi Capitals,Punjab Kings,Jaipur,6,5,6,206,10.486957,7.200000,1
251121,Delhi Capitals,Punjab Kings,Jaipur,5,4,6,206,10.448276,7.500000,1
251122,Delhi Capitals,Punjab Kings,Jaipur,-1,3,6,206,10.666667,-2.000000,1

In [90]:
final_df = final_df.sample(final_df.shape[0])

In [91]:
final_df.sample()

,team_batting,team_bowling,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,results
241007,Chennai Super Kings,Lucknow Super Giants,Lucknow,110,88,9,166,10.6875,7.5,1

- <b> Model Development

In [92]:
x = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]

In [93]:
import pandas as pd
import numpy as np
# import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.metrics import accuracy_score, classification_report

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
x_train, x_test,y_train,t_test = train_test_split(x,y,test_size=0.2,random_state=42)

NameError: name 'train_test_split' is not defined